fixup

diff --git a/integration-tests/rapidast-check.yaml b/integration-tests/rapidast-check.yaml
--- a/integration-tests/rapidast-check.yaml
+++ b/integration-tests/rapidast-check.yaml
@@ -44,18 +44,30 @@ spec:
             secretKeyRef:
               name: "$(params.KUBECONFIG_SECRET)"
               key: kubeconfig
-      args:
-        - --targets
-        - $(params.PORT_FORWARD_TARGETS[*])
       script: |
         #!/usr/bin/env bash
         set -ex
 
         cat <<< "$KUBECONFIG_VALUE" > "$KUBECONFIG"
         echo "Wrote kubeconfig for new environment to $KUBECONFIG"
+
+        check_pid_listening_port() {
+            local pid=$1
+            # checks that PID has at least one local port open
+            if lsof -a -p "${pid}" -iTCP -sTCP:LISTEN >/dev/null 2>&1; then
+                return 0 # PID has a listening port
+            else
+                return 1 # PID does not have a listening port
+            fi
+        }
         
-        for t in "${targets[@]}"; do
-          oc port-forward $t &
+        for t in "$(params.PORT_FORWARD_TARGETS[*]; do
+          oc port-forward ${t} &
+          PID=$!
+          timeout 30s check_pid_listening_port ${PID} || {
+            echo "oc port-foward failed to open local port"
+            exit 1
+          }
         done
 
         touch /shared/port-forward-ready
